# conditional CIFAR10 generation with SN and projection discriminator
batchsize: 64
disc_update: 2
epochs: 220
summary_every_n_steps: 400
save_every_n_steps: 2000
truncation: 0.5
n_classes: 16
dataset_name: cface_train_128.tfrecords

model:
  generator:
    lib: generator.snresnet_128
    args:
      dim_z: 128
      bottom_width: 4
      ch: 32
      n_classes: 16


  discriminator:
      lib: discriminator.snresnet_128
      args:
        ch: 32
        n_classes: 16

dataset:
  img_size: 128

optimizer:
  generator:
    learning_rate: 0.00008
    beta_1: 0.0
    beta_2: 0.9

  discriminator:
    learning_rate: 0.0002
    beta_1: 0.0
    beta_2: 0.9